
# stages:          # List of stages for jobs, and their order of execution
#   - build
#   - deploy

# build:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
#     - echo "Compiling the code..."
#     - echo "Compile complete."
#   tags:
#     - zentao
#   only:
#     - main

deploy:    
  stage: deploy  
  environment: production
  script:
    - whoami
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "This project's root directory is ${CI_PROJECT_NAME}"
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "Deploying application..."
    - echo ${RUNNER_PASSWD} | sudo -S cp -fr ../${CI_PROJECT_NAME} /home/product/
    - echo ${RUNNER_PASSWD} | sudo -S chmod -R 777  tmp
    - echo "Application successfully deployed."
  tags:
    - zentao
  only:
    - main
  artifacts:
    untracked: true
    when: on_success
    expire_in: 30 days
    paths:
      - ../${CI_PROJECT_NAME}
    exclude:
      - .gitignore
      - .gitlab-ci.yml
