stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  PROJECT: "121.89.178.134:5050/15-test-group/zentaopms"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run --privileged --rm tonistiigi/binfmt --install arm64
    - docker buildx create gitlab_builder --use
    - docker buildx build --tag $PROJECT/zentaopms-arm64v8:$(date "+%Y-%m-%d") --platform linux/arm64 --load .
    - docker buildx build --tag $PROJECT/zentaopms-amd64:$(date "+%Y-%m-%d") --platform linux/mad64 --load .
    - docker tag $PROJECT/zentaopms-arm64v8:$(date "+%Y-%m-%d") $PROJECT/zentaopms-arm64v8:latest
    - docker tag $PROJECT/zentaopms-amd64:$(date "+%Y-%m-%d") $PROJECT/zentaopms-amd64:latest
    - docker push $PROJECT/zentaopms-arm64v8:$(date "+%Y-%m-%d")
    - docker push $PROJECT/zentaopms-arm64v8:latest
    - docker push $PROJECT/zentaopms-amd64:$(date "+%Y-%m-%d")
    - docker push $PROJECT/zentaopms-amd64:latest

deploy:    
  stage: deploy  
  environment: production
  tags:
    - zentao
  only:
    - main
  script:
    - whoami
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "This project's root directory is ${CI_PROJECT_NAME}"
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "Deploying application..."
    - echo ${RUNNER_PASSWD} | sudo -S cp -fr ../${CI_PROJECT_NAME} ${PROJECT_FULLPATH}
    - echo "Fix /tmp access issue..."
    - echo sudo chmod -R 777  ${PROJECT_FULLPATH}/${CI_PROJECT_NAME}/tmp
    - echo "Change database..."
    - db/myDbChange/updateDbServer.sh
    - echo "Application successfully deployed!"
  artifacts:
    name: ${CI_PROJECT_NAME}
    untracked: true
    when: on_success
    expire_in: 1 days
    paths:
      - ../${CI_PROJECT_NAME}
    exclude:
      - .gitignore
      - .gitlab-ci.yml
      - .git/**/*
      - .git


