deploy:    
  stage: deploy  
  environment: production
  script:
    - whoami
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "This project's root directory is ${CI_PROJECT_NAME}"
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "Deploying application..."
    - echo ${RUNNER_PASSWD} | sudo -S cp -fr ../${CI_PROJECT_NAME} ${PROJECT_FULLPATH}
    - echo "Fix /tmp access issue..."
    - echo sudo chmod -R 777  ${PROJECT_FULLPATH}/${CI_PROJECT_NAME}/tmp
    - echo "Change database..."
    - mysql -u ${DATABASE_USER} -p${DATABASE_PASSWORD} -D ${DATABASE} < ${PROJECT_FULLPATH}/${CI_PROJECT_NAME}/db/myDbChange/allChangeServer.sql
    - echo "Application successfully deployed!"
  tags:
    - zentao
  only:
    - main
  artifacts:
    name: ${CI_PROJECT_NAME}
    untracked: true
    when: on_success
    expire_in: 1 days
    paths:
      - ../${CI_PROJECT_NAME}
    exclude:
      - .gitignore
      - .gitlab-ci.yml
      - .git/**/*
      - .git

