services:
  app:
    image: zentaopms:latest
    container_name: app
    ports:
      - "8808:80"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: zentao_db
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - zentao:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zentao_db

volumes:
  zentao:
    name: zentao
