services:
  app-0:
    image: 121.89.178.134:5050/15-test-group/zentaopms/zentaopms-amd64:latest
    container_name: app-0
    ports:
      - "50000:80"
    environment:
      MYSQL_HOST: database-0
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: zentao_db
    depends_on:
      - database-0
  database-0:
    image: amd64/mysql:8.0
    container_name: database-0
    ports:
      - "33000:3306"
    volumes:
      - zentao-0:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zentao_db

volumes:
  zentao-0:
    name: zentao-0